### ISSUE TITLE
Extra parameters passed to parent construct: $data in vendor/feedoptimise/magento2-catalog-export/src/Helper/Currency.php

### ISSUE THREAD

**Issue by eliacimdavila** [feedoptimise/magento2-catalog-export#1]
We tried to install the module in our **Magento 2.4.5-p1**, but when we compiled, it threw us this error:

> Extra parameters passed to parent construct: $data. File: vendor/feedoptimise/magento2-catalog-export/src/Helper/Currency.php

We reviewed the code, and this happened because in **src/Helper/Currency.php** **Line 22** is sending as parameter **$data**, but parent in **Magento\Framework\App\Helper\AbstractHelper** only receive one parameter, **$context.**

![image](https://github.com/feedoptimise/magento2-catalog-export/assets/21063809/14df2696-8875-4d8b-9bea-beb68262ab91)

![image](https://github.com/feedoptimise/magento2-catalog-export/assets/21063809/de4dc9c7-1351-4b0b-a106-8faf2d9d4b47)

**Comment by adrchw** [comment]
Correct, thanks for the fix! Merged to 1.2.39
